"""
extract_model.py - Extract DAPD-SVM model for ESP32-S3 deployment.

Reads the sklearn Pipeline (.joblib) and mask (.npy) from this directory,
produces:
  1. ../src/svm_arrays.c              - C source with all float arrays
  2. ../include/zoecare/rx/svm_params.h  - C header with dimensions and externs

Support vectors are stored as float32.

Usage:
  Place the .joblib and .npy files in this directory (model/), then:
    python extract_model.py

  If multiple .joblib files are present, the most recently modified is used.
  You can also specify explicitly:
    python extract_model.py my_model.joblib my_mask.npy
"""

import os
import sys
import glob
import warnings
import numpy as np

warnings.filterwarnings("ignore")

MODEL_DIR  = os.path.dirname(os.path.abspath(__file__))
COMPONENT_DIR = os.path.abspath(os.path.join(MODEL_DIR, ".."))
OUT_C      = os.path.join(COMPONENT_DIR, "src", "svm_arrays.c")
OUT_H      = os.path.join(COMPONENT_DIR, "include", "zoecare", "rx", "svm_params.h")


def find_latest(pattern):
    matches = glob.glob(os.path.join(MODEL_DIR, pattern))
    if not matches:
        return None
    return max(matches, key=os.path.getmtime)


# --- Resolve paths from args or auto-detect ---
if len(sys.argv) == 3:
    model_path = sys.argv[1] if os.path.isabs(sys.argv[1]) else os.path.join(MODEL_DIR, sys.argv[1])
    mask_path  = sys.argv[2] if os.path.isabs(sys.argv[2]) else os.path.join(MODEL_DIR, sys.argv[2])
elif len(sys.argv) == 1:
    model_path = find_latest("*.joblib")
    mask_path  = find_latest("*.npy")
    if not model_path:
        print("ERROR: no .joblib file found in model/. Place the model file here or pass it as argument.")
        sys.exit(1)
    if not mask_path:
        print("ERROR: no .npy file found in model/. Place the mask file here or pass it as argument.")
        sys.exit(1)
    print(f"Auto-detected model: {os.path.basename(model_path)}")
    print(f"Auto-detected mask:  {os.path.basename(mask_path)}")
else:
    print("Usage: python extract_model.py [model.joblib mask.npy]")
    sys.exit(1)

# --- Load model ---
import joblib

print("Loading model...")
model = joblib.load(model_path)
assert hasattr(model, "steps"), "Expected a sklearn Pipeline"

scaler = model.named_steps["standardscaler"]
svc    = model.named_steps["svc"]

sv        = svc.support_vectors_.astype(np.float32)
dual_coef = svc.dual_coef_[0].astype(np.float32)
gamma     = float(svc._gamma)
intercept = float(svc.intercept_[0])
n_sv, n_features = sv.shape

scaler_mean  = scaler.mean_.astype(np.float32)
scaler_scale = scaler.scale_.astype(np.float32)

print(f"SVC: N_SV={n_sv}, N_FEATURES={n_features}, gamma={gamma:.12e}, intercept={intercept:.12e}")

# --- Load mask ---
mask = np.load(mask_path)
mask_indices = np.where(mask)[0].astype(np.uint16)
assert len(mask_indices) == n_features, (
    f"Mask true count ({len(mask_indices)}) != N_FEATURES ({n_features})"
)
print(f"Mask: {mask.shape[0]} total -> {len(mask_indices)} selected features")


# --- Helpers ---
def fmt_float_array(name, arr, per_line=8):
    lines = [f"const float {name}[{len(arr)}] = {{"]
    for i in range(0, len(arr), per_line):
        chunk = arr[i:i+per_line]
        vals = ", ".join(f"{v:.10e}f" for v in chunk)
        lines.append(f"    {vals},")
    lines.append("};")
    return "\n".join(lines)

def fmt_uint16_array(name, arr, per_line=16):
    lines = [f"const uint16_t {name}[{len(arr)}] = {{"]
    for i in range(0, len(arr), per_line):
        chunk = arr[i:i+per_line]
        vals = ", ".join(str(int(v)) for v in chunk)
        lines.append(f"    {vals},")
    lines.append("};")
    return "\n".join(lines)


# --- Write svm_arrays.c ---
sv_flat = sv.flatten()
model_basename = os.path.basename(model_path)

with open(OUT_C, "w") as f:
    f.write(f"/* Auto-generated by model/extract_model.py from {model_basename} - DO NOT EDIT */\n")
    f.write('#include "zoecare/rx/svm_params.h"\n\n')
    f.write(fmt_float_array("svm_dual_coef", dual_coef))
    f.write("\n\n")
    f.write(fmt_float_array("svm_sv_data", sv_flat))
    f.write("\n\n")
    f.write(fmt_float_array("svm_scaler_mean", scaler_mean))
    f.write("\n\n")
    f.write(fmt_float_array("svm_scaler_scale", scaler_scale))
    f.write("\n\n")
    f.write(fmt_uint16_array("svm_mask_indices", mask_indices))
    f.write("\n")

print(f"Written: {OUT_C} ({os.path.getsize(OUT_C):,} bytes)")


# --- Write svm_params.h ---
with open(OUT_H, "w") as f:
    f.write(f"/* Auto-generated by model/extract_model.py from {model_basename} - DO NOT EDIT */\n")
    f.write("#ifndef ZC_ZF_SVM_PARAMS_H\n")
    f.write("#define ZC_ZF_SVM_PARAMS_H\n\n")
    f.write("#include <stdint.h>\n\n")

    f.write(f"#define SVM_N_SV        {n_sv}\n")
    f.write(f"#define SVM_N_FEATURES  {n_features}\n")
    f.write(f"#define SVM_FLAT_SIZE   {mask.shape[0]}\n")
    f.write(f"#define SVM_MASK_SIZE   {n_features}\n\n")

    f.write(f"#define SVM_GAMMA       {gamma:.15e}f\n")
    f.write(f"#define SVM_INTERCEPT   {intercept:.15e}f\n\n")

    f.write("// DAPD dimensions used during training\n")
    f.write("#define SVM_DAPD_K        13\n")
    f.write("#define SVM_DAPD_M        52\n")
    f.write("#define SVM_DAPD_N_BINS   17\n")
    f.write("#define SVM_DAPD_N_SM     4\n")
    f.write("#define SVM_DAPD_N_GROUPS 9\n")
    f.write("#define SVM_TRANSPOSE_SIZE (SVM_DAPD_K * SVM_DAPD_M * SVM_DAPD_N_SM * SVM_DAPD_N_BINS)\n\n")

    f.write("// Float arrays (defined in svm_arrays.c)\n")
    f.write("extern const float    svm_dual_coef[SVM_N_SV];\n")
    f.write("extern const float    svm_sv_data[SVM_N_SV * SVM_N_FEATURES];\n")
    f.write("extern const float    svm_scaler_mean[SVM_N_FEATURES];\n")
    f.write("extern const float    svm_scaler_scale[SVM_N_FEATURES];\n")
    f.write("extern const uint16_t svm_mask_indices[SVM_MASK_SIZE];\n\n")

    f.write("#endif // ZC_ZF_SVM_PARAMS_H\n")

print(f"Written: {OUT_H}")

# --- Summary ---
sv_size    = n_sv * n_features * 4
other_size = (n_sv + n_features * 2) * 4 + n_features * 2
total      = sv_size + other_size
print(f"\n=== Done. Flash usage ===")
print(f"  SVs (float32):  {sv_size:>10,} bytes ({sv_size/1024:.1f} KB)")
print(f"  Other arrays:   {other_size:>10,} bytes ({other_size/1024:.1f} KB)")
print(f"  Total:          {total:>10,} bytes ({total/1024/1024:.2f} MB)")
print(f"\nNext: rebuild firmware with 'dev> build zoefall_rx'")
