/*
 * Automatically generated file. DO NOT EDIT.
 * Espressif IoT Development Framework (ESP-IDF)  Configuration Header
 */
#pragma once
#define CONFIG_ZC_ZF_SEND_REPORT_TASK_STACK_DEPTH 5000
#define CONFIG_ZC_ZF_REPORT_STATUS_TASK_STACK_DEPTH 5000
#define CONFIG_ZC_ZF_WIFI_AP_SSID "ZoeFall7DA4"
#define CONFIG_ZC_ZF_WIFI_AP_PASSWORD "a9qgwZYn5ApgrgXxZD%q"
#define CONFIG_ZC_ZF_WIFI_RECONNECT_DELAY 30
#define CONFIG_ZC_ZF_REPORT_STATUS_DELAY 60
#define CONFIG_ZC_ZF_CSI_RATE 100
#define CONFIG_ZC_ZF_TX_UDP_TASK_STACK_DEPTH 3000
#define CONFIG_ZC_ZF_TX_TB_ACCESS_TOKEN "dezkPw3ODEEZy2oGyMKl"
#define CONFIG_ZC_ZF_TX_UPSTREAM_SSID "DVIPro"
#define CONFIG_ZC_ZF_TX_UPSTREAM_PASSWORD "Jrd729kz"
