/* Auto-generated by py_model/sklearn/extract_model.py - DO NOT EDIT */
#ifndef SVM_PARAMS_H
#define SVM_PARAMS_H

#include <stdint.h>

#define SVM_N_SV        1584
#define SVM_N_FEATURES  126
#define SVM_FLAT_SIZE   7956   // 7956 = K * N_GROUPS * N_SM * N_BINS after median reduction 
#define SVM_MASK_SIZE   126

#define SVM_GAMMA       7.936507936507865e-03f
#define SVM_INTERCEPT   -8.428141400927597e-01f

// DAPD dimensions used during training
#define SVM_DAPD_K       13
#define SVM_DAPD_M       52
#define SVM_DAPD_N_BINS  17
#define SVM_DAPD_N_SM    4
#define SVM_DAPD_N_GROUPS 9    // median reduction: M split into 9 groups
#define SVM_TRANSPOSE_SIZE (SVM_DAPD_K * SVM_DAPD_M * SVM_DAPD_N_SM * SVM_DAPD_N_BINS) // 45968: pre-reduction buffer

// Float arrays (defined in svm_arrays.c)
extern const float    svm_dual_coef[SVM_N_SV];
extern const float    svm_sv_data[SVM_N_SV * SVM_N_FEATURES];
extern const float    svm_scaler_mean[SVM_N_FEATURES];
extern const float    svm_scaler_scale[SVM_N_FEATURES];
extern const uint16_t svm_mask_indices[SVM_MASK_SIZE];

#endif // SVM_PARAMS_H
